/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-04-29 15:35:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.5.RELEASE.jar", Long.valueOf(1586425206315L));
    _jspx_dependants.put("jar:file:/C:/Users/IMS/Desktop/HACKING/WEB-DEVELOPMENT/JAVA/CH33TZ-SPRING-BOOT-CRUD/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ch33tz/WEB-INF/lib/spring-webmvc-5.2.5.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1585045452000L));
    _jspx_dependants.put("jar:file:/C:/Users/IMS/Desktop/HACKING/WEB-DEVELOPMENT/JAVA/CH33TZ-SPRING-BOOT-CRUD/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ch33tz/WEB-INF/lib/spring-webmvc-5.2.5.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1585045452000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1587740644386L));
    _jspx_dependants.put("jar:file:/C:/Users/IMS/Desktop/HACKING/WEB-DEVELOPMENT/JAVA/CH33TZ-SPRING-BOOT-CRUD/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ch33tz/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Cinzel&family=Monoton&family=Open+Sans+Condensed:wght@300&family=Righteous&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"data:image/x-icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkXxnJY94Z2aPeGdmj3hnZo94Z2aPeGdmj3hnZo94Z2aPeGdmjnhjJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIp1ahiPeGa2j3lnzJB7aOKSfWvtkn1r7ZB7aOKPeWfMjnlltZB6ZBcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACplIGk1MGw/9TBsP+plIGkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAl4Fs2495Zv+PeWb/j3lm/495Zv+PeWb/j3lm/495Zv+PeWb/j3lm/495Zv+PeWb/j3lm/5GDcv+Ti37/l4Fs25yGcNuPeWb/j3lm/495Zv+PeWb/j3lm/495Zv+PeWb/j3lm/495Zv+PeWb/j3lm/495Zv+Rg3L/k4t+/5yGcNu5ooek/+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv+5ooekuaKHpP/owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML/uaKHpLmih6T/6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC/7mih6S5ooek/+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv+5ooekuaKHpP/owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML/uaKHpLmih6T/6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC/7mih6S5ooek/+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv+5ooekuaKHpP/owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML//+jC///owv//6ML/uaKHpKyWfYvErZHDxK2Rw8StkcPErZHDxK2Rw8StkcPErZHDxK2Rw8StkcPErZHDxK2Rw8StkcPErZHDxK2Rw6yWfYsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAOAHAADgBwAA/D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAA==\" />\r\n");
      out.write("<script\r\n");
      out.write("    src=\"https://code.jquery.com/jquery-3.5.0.slim.js\"\r\n");
      out.write("    integrity=\"sha256-sCexhaKpAfuqulKjtSY7V9H7QT0TCN90H+Y5NlmqOUE=\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("<title>Welcome</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\t body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        div.main-container {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        div.title-container {\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1.main-title {\r\n");
      out.write("            font-family: 'Monoton', cursive;\r\n");
      out.write("            color: #902828;\r\n");
      out.write("            letter-spacing: 4px;\r\n");
      out.write("            font-size: 4em;\r\n");
      out.write("            margin: .1em;\r\n");
      out.write("            padding: .1em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        div.operations-container {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        div[class^=\"operation-item\"] {\r\n");
      out.write("            width: 49.67%;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("            border: .2vw solid #000;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            transition: background-color linear .3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        div.operation-item-c { background-color: #ff9100; border-right: none; }\r\n");
      out.write("        div.operation-item-r { background-color: #ffd000; }\r\n");
      out.write("        div.operation-item-u { background-color: #00f7ff; border-right: none; border-top: none; }\r\n");
      out.write("        div.operation-item-d { background-color: #ff0000; border-top: none;}\r\n");
      out.write("\r\n");
      out.write("        div.operation-label {\r\n");
      out.write("            font-family: 'Open Sans Condensed', sans-serif;\r\n");
      out.write("            font-size: 4em;\r\n");
      out.write("            border: 2px solid #fff;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            width: 40%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            border-radius: 80px;\r\n");
      out.write("            transition: color, border linear .3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.operation-label a {\r\n");
      out.write("        \ttext-decoration: none;\r\n");
      out.write("        \tcolor: inherit !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 1000px) {\r\n");
      out.write("            \r\n");
      out.write("            div[class^=\"operation-item\"] {\r\n");
      out.write("                width: 99.968%;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            div.operation-item-c,\r\n");
      out.write("            div.operation-item-u {\r\n");
      out.write("                border-right: .2vw solid #000;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<h1>Welcome to CH33TZ crud</h1>\r\n");
      out.write("\r\n");
      out.write("<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/list\">List all users</a><br>\r\n");
      out.write("<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/add\">Create new user</a><br>\r\n");
      out.write("<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/list\">Update user</a><br>\r\n");
      out.write("<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/list\">Delete user</a> -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"main-container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"title-container\">\r\n");
      out.write("            <h1 class=\"main-title\">CH33TZ</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"operations-container\">\r\n");
      out.write("            <div class=\"operation-item-c\">\r\n");
      out.write("                <div class=\"operation-label\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/add\">CREATE</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"operation-item-r\">\r\n");
      out.write("                <div class=\"operation-label\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/list\">READ</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"operation-item-u\">\r\n");
      out.write("                <div class=\"operation-label\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/list\">UPDATE</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"operation-item-d\">\r\n");
      out.write("                <div class=\"operation-label\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/list\">DELETE</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("            let operationItems = $('div[class^=\"operation-item\"]').children();\r\n");
      out.write("\r\n");
      out.write("            operationItems.each(function() {\r\n");
      out.write("                let parentClassName = $(this).parent().attr('class');\r\n");
      out.write("\r\n");
      out.write("                switch(parentClassName) {\r\n");
      out.write("\r\n");
      out.write("                    // Orange\r\n");
      out.write("                    case 'operation-item-c': \r\n");
      out.write("\r\n");
      out.write("                        $(this).hover(\r\n");
      out.write("                            function() {\r\n");
      out.write("                                $(this).css({\r\n");
      out.write("                                    \"border-color\" : \"#ff9100\",\r\n");
      out.write("                                    \"color\" : \"#ff9100\"\r\n");
      out.write("                                });\r\n");
      out.write("                                $(this).parent().css(\"background\", \"#fff\");\r\n");
      out.write("                            }, \r\n");
      out.write("                            function() {\r\n");
      out.write("                                $(this).css({\r\n");
      out.write("                                    \"border-color\" : \"#fff\",\r\n");
      out.write("                                    \"color\" : \"#fff\"\r\n");
      out.write("                                });\r\n");
      out.write("                                $(this).parent().css(\"background\", \"#ff9100\");\r\n");
      out.write("                            }\r\n");
      out.write("                        );\r\n");
      out.write("\r\n");
      out.write("                    break;\r\n");
      out.write("\r\n");
      out.write("                    // Yellow \r\n");
      out.write("                    case 'operation-item-r': \r\n");
      out.write("\r\n");
      out.write("                        $(this).hover(\r\n");
      out.write("                            function() {\r\n");
      out.write("                                $(this).css({\r\n");
      out.write("                                    \"border-color\" : \"#ffd000\",\r\n");
      out.write("                                    \"color\" : \"#ffd000\"\r\n");
      out.write("                                });\r\n");
      out.write("                                $(this).parent().css(\"background\", \"#fff\");\r\n");
      out.write("                            }, \r\n");
      out.write("                            function() {\r\n");
      out.write("                                $(this).css({\r\n");
      out.write("                                    \"border-color\" : \"#fff\",\r\n");
      out.write("                                    \"color\" : \"#fff\"\r\n");
      out.write("                                });\r\n");
      out.write("                                $(this).parent().css(\"background\", \"#ffd000\");\r\n");
      out.write("                            }\r\n");
      out.write("                        );\r\n");
      out.write("\r\n");
      out.write("                    break;\r\n");
      out.write("\r\n");
      out.write("                    // Blue\r\n");
      out.write("                    case 'operation-item-u': \r\n");
      out.write("\r\n");
      out.write("                        $(this).hover(\r\n");
      out.write("                            function() {\r\n");
      out.write("                                $(this).css({\r\n");
      out.write("                                    \"border-color\" : \"#00f7ff\",\r\n");
      out.write("                                    \"color\" : \"#00f7ff\"\r\n");
      out.write("                                });\r\n");
      out.write("                                $(this).parent().css(\"background\", \"#fff\");\r\n");
      out.write("                            }, \r\n");
      out.write("                            function() {\r\n");
      out.write("                                $(this).css({\r\n");
      out.write("                                    \"border-color\" : \"#fff\",\r\n");
      out.write("                                    \"color\" : \"#fff\"\r\n");
      out.write("                                });\r\n");
      out.write("                                $(this).parent().css(\"background\", \"#00f7ff\");\r\n");
      out.write("                            }\r\n");
      out.write("                        );\r\n");
      out.write("\r\n");
      out.write("                    break;\r\n");
      out.write("\r\n");
      out.write("                    // Red\r\n");
      out.write("                    case 'operation-item-d': \r\n");
      out.write("\r\n");
      out.write("                        $(this).hover(\r\n");
      out.write("                            function() {\r\n");
      out.write("                                $(this).css({\r\n");
      out.write("                                    \"border-color\" : \"#ff0000\",\r\n");
      out.write("                                    \"color\" : \"#ff0000\"\r\n");
      out.write("                                });\r\n");
      out.write("                                $(this).parent().css(\"background\", \"#fff\");\r\n");
      out.write("                            }, \r\n");
      out.write("                            function() {\r\n");
      out.write("                                $(this).css({\r\n");
      out.write("                                    \"border-color\" : \"#fff\",\r\n");
      out.write("                                    \"color\" : \"#fff\"\r\n");
      out.write("                                });\r\n");
      out.write("                                $(this).parent().css(\"background\", \"#ff0000\");\r\n");
      out.write("                            }\r\n");
      out.write("                        );\r\n");
      out.write("\r\n");
      out.write("                    break;\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /index.jsp(100,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /index.jsp(100,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(100,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
